<?php
/**
 * @category	Solide Webservices
 * @package		CustomSuccessPage
 */
?>
<?php if(Mage::getStoreConfig('customsuccesspage/ordered/items_ordered')): ?>
<div class="csp-section csp-ordered-items">
	<?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', Mage::helper('customsuccesspage')->returnOrder())): ?>
	<script type="text/javascript">
	//<![CDATA[
	function giftMessageToogle(giftMessageIdentifier)
	{
		var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
		var container = $('order-item-gift-message-'+giftMessageIdentifier);
		var row = $('order-item-row-'+giftMessageIdentifier);
		if(link.expanded) {
			link.expanded = false;
			link.removeClassName('expanded');
			if(container.hasClassName('last')) {
				row.addClassName('last');
			}
			container.hide();
		} else {
			link.expanded = true;
			link.addClassName('expanded');
			if(container.hasClassName('last')) {
				row.removeClassName('last');
			}
			container.show();
		}

		return false;
	}
	//]]>
	</script>
	<?php endif; ?>
	<?php $_order = Mage::helper('customsuccesspage')->returnOrder() ?>
	<h2 class="table-caption"><?php echo (Mage::getStoreConfig('customsuccesspage/ordered/items_ordered_title') ? Mage::getStoreConfig('customsuccesspage/ordered/items_ordered_title') : $this->__('Items Ordered')); ?></h2>
	<?php echo $this->getChildHtml('order_items') ?>
	<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
	<div class="order-additional order-gift-message">
		<h2 class="sub-title"><?php echo $this->__('Gift Message for This Order') ?></h2>
		<?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
		<dl class="gift-message">
			<dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getSender()) ?></dt>
			<dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
			<dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
		</dl>
	</div>
	<?php endif; ?>
</div>
<?php endif; ?>
