<?php
/**
 * @category	Solide Webservices
 * @package		CustomSuccessPage
 */
?>
<div class="block block-subscribe">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
			<div class="form-subscribe-header">
                <label for="newsletter"><?php echo (Mage::getStoreConfig('customsuccesspage/newsletter/newsletter_intro') ? Mage::getStoreConfig('customsuccesspage/newsletter/newsletter_intro') : $this->__('Please consider signing up for our newsletter.')); ?></label>
            </div>
            <div class="input-box">
               <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
